"""empty message

Revision ID: 50aec3ea8f70
Revises: 98410fd83698
Create Date: 2023-05-01 00:05:00.867881

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '50aec3ea8f70'
down_revision = '98410fd83698'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
