"""empty message

Revision ID: 98410fd83698
Revises: 662fc3395459
Create Date: 2023-04-30 23:27:00.252866

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '98410fd83698'
down_revision = '662fc3395459'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('snaps',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.Column('caption', sa.Text(), nullable=True),
    sa.Column('creator_id', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['creator_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('snapshot_content',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.Column('photo_url', sa.String(), nullable=True),
    sa.Column('snap_id', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['snap_id'], ['snaps.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('snapshot_content')
    op.drop_table('snaps')
    # ### end Alembic commands ###
