"""empty message

Revision ID: b08322495ba4
Revises: d1ca4de0fd70
Create Date: 2023-04-25 12:27:52.277081

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b08322495ba4'
down_revision = 'd1ca4de0fd70'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('photo_content_posts', sa.Column('post_id', sa.BigInteger(), nullable=True))
    op.create_foreign_key(None, 'photo_content_posts', 'photo_posts', ['post_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'photo_content_posts', type_='foreignkey')
    op.drop_column('photo_content_posts', 'post_id')
    # ### end Alembic commands ###
